### ISSUE TITLE
Cannot to log in on server

### ISSUE THREAD

**Issue by dras1911** [opentibiabr/myaac-tibia12-login#1]
Cannot to log in on server with this plugin and otbr tools tibia12. 
Char list popup but if I want to enter on server client crash.

**Comment by MajestyOTBR** [comment]
Use MyAAC + MyAAC login.php for Tibia 12.
To login on localhost with client 12, use 127.0.0.1_client.exe.

**Comment by dras1911** [comment]
Using MyAAC and MyAAC login.php for Tibia 12 also using 127.0.0.1_client.exe and still cannot to log in.

**Comment by MajestyOTBR** [comment]
If you are using UniformServer, you need to unzip MyAAC folders and archives directly on www folder.

**Comment by MajestyOTBR** [comment]
If you are using UniformServer, you need to unzip MyAAC folders and archives directly on www folder, then install MyAAC, install MyAAC login.php for client 12 to work.

**Comment by MajestyOTBR** [comment]
I posted a tutorial about this: https://forums.otserv.com.br/index.php?/forums/topic/167681-windowsmysqlotservbr-global-uniform-server%C2%A0-myaac/
